[project]
name = "openlistapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fsspec>=2025.10.0",
    "httpx>=0.28.1",
    "pyotp>=2.9.0",
]
